CREATE TABLE tb_channels (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    yt_id      VARCHAR(50) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    sync_at    TIMESTAMP(6) WITH TIME ZONE,

    CONSTRAINT tb_channels_yt_id_uk UNIQUE(yt_id)
);

-- Usuário com apenas a role ADMIN
INSERT INTO tb_channels (yt_id) VALUES ('UC6g6eok10NJGYgenHO-0Oew');