CREATE TABLE tb_channels (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    yt_id           VARCHAR(50) NOT NULL,
    next_page_token VARCHAR(255),
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    sync_at         TIMESTAMP(6) WITH TIME ZONE,

    CONSTRAINT tb_channels_yt_id_uk UNIQUE(yt_id)
);

CREATE TABLE tb_videos (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    yt_id        VARCHAR(255) NOT NULL,
    channel_id   BIGINT NOT NULL,
    title        VARCHAR(255),
    description  VARCHAR(255),
    thumbnail    VARCHAR(255),
    sync_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    published_at TIMESTAMP(6) WITH TIME ZONE,
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT tb_videos_yt_id_uk UNIQUE(yt_id),
    CONSTRAINT tb_videos_channel_fk FOREIGN KEY (channel_id) REFERENCES tb_channels
);

CREATE TABLE tb_comments (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    yt_comment_id        VARCHAR(255) NOT NULL,
    video_id             BIGINT NOT NULL,
    author_name          VARCHAR(255),
    author_channel_id    VARCHAR(255),
    text                 TEXT,
    like_count           INTEGER DEFAULT 0,
    published_at         TIMESTAMP(6) WITH TIME ZONE,
    updated_at           TIMESTAMP(6) WITH TIME ZONE,
    created_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    sync_at              TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT tb_comments_yt_comment_id_uk UNIQUE(yt_comment_id),
    CONSTRAINT tb_comments_video_fk FOREIGN KEY (video_id) REFERENCES tb_videos ON DELETE CASCADE
);

-- Create indexes separately (INDEX keyword in CREATE TABLE is not standard SQL)
CREATE INDEX idx_comments_video_id ON tb_comments(video_id);
CREATE INDEX idx_comments_published_at ON tb_comments(published_at);

-- Usuário com apenas a role ADMIN
INSERT INTO tb_channels (yt_id) VALUES ('UC6g6eok10NJGYgenHO-0Oew');