CREATE TABLE tb_channels (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    yt_id           VARCHAR(50) NOT NULL,
    next_page_token VARCHAR(255),
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    sync_at         TIMESTAMP(6) WITH TIME ZONE,

    CONSTRAINT tb_channels_yt_id_uk UNIQUE(yt_id)
);

CREATE TABLE tb_videos (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    yt_id        VARCHAR(255) NOT NULL,
    channel_id   BIGINT NOT NULL,
    title        VARCHAR(255),
    description  VARCHAR(255),
    thumbnail    VARCHAR(255),
    sync_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    published_at TIMESTAMP(6) WITH TIME ZONE,
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT tb_videos_yt_id_uk UNIQUE(yt_id),
    CONSTRAINT tb_videos_channel_fk FOREIGN KEY (channel_id) REFERENCES tb_channels
);

-- Usuário com apenas a role ADMIN
INSERT INTO tb_channels (yt_id) VALUES ('UC6g6eok10NJGYgenHO-0Oew');